// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameMoves, GameMovesData, GameMovesTableId } from "./tables/GameMoves.sol";
import { Record, RecordData, RecordTableId } from "./tables/Record.sol";
import { NFTs, NFTsTableId } from "./tables/NFTs.sol";
