// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum Color {
  WHITE,
  BLACK
}

enum GameState {
  DOES_NOT_EXIST,
  WON,
  LOST,
  ONGOING
}
