// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Color } from "./../Types.sol";

interface IGameStateManagementSystem {
  function setGameInit(bytes32 gameId, uint playerColor) external;

  function playTurn(bytes32 gameId, string memory fenCode) external;

  function endGame(bytes32 gameId, Color winner, string memory ipfsHash) external;
}
